spring.application.name=kuriq
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# MySQL 연결
spring.datasource.url=jdbc:mysql://localhost:3306/kuriq?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=kuriq-super-secret-key-2026-project-very-long-secret-key-123456789
jwt.expiration=3600000

# MySQL 설정



# JWT 설정
jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=1209600000

# 비밀번호 재설정 시 이메일 발송 로직 SMTP 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hyunjung26@skuniv.ac.kr
spring.mail.password=fniy xpjl olaf oguz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 카카오 소셜 로그인 키 설정
oauth.kakao.client-id=5d4cfd50058b6907aa5b453330e7e1c8
oauth.kakao.redirect-uri=https://startup-chug-trembling.ngrok-free.dev/api/v1/auth/social/callback
oauth.kakao.client-secret=MmkqKQAlxUe6U1qA9cB2nT5T4eNP0ZFX